### Get Token from Keycloak
POST http://{{slm_host}}:7080/auth/realms/fabos/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=fabos&password=password&client_id=self-service-portal

> {%
  client.global.set("auth_token", response.body.access_token);
%}

### Get Resources
GET http://{{slm_host}}:9010/resources
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Create Resources
PUT http://{{slm_host}}:9010/resources?resourceUsername=username&resourcePassword=password&resourceHostname=test-host-01&resourceIp=192.168.0.1&resourceConnectionType=ssh
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Delete Resource
DELETE http://{{slm_host}}:9010/resources/b4b6c763-6e98-4701-8bb7-8ee4b0dd98e0
Content-Type: application/json
Authorization: Bearer {{auth_token}}
